data:
  resize: 1024
  annotation_mean: True
  augment: rotation  # False, d4, rotation
  augment_prob: 0.95
  positive_only: False
  y_sym_mode: bilinear

model:
  encoder: maxvit_tiny_tf_512.in1k
  pretrained: True
  decoder_channels: [256, 128, 64, 32, 16]
  load: 
  dropout: 0.0

kfold:
  k: 10
  folds: 0,2,5 # 3,4 have weight_decay=1e-4, these have 1e-2

train:
  weight_decay: 1e-2
  batch_size: 4
  accumulate: 2
  num_workers: 2
  loss: bce

val:
  per_epoch: 1
  th: 0.45

test:
  th: 0.45

scheduler:
  - linear:
      lr_start: 1e-8
      lr_end: 8e-4
      epoch_end: 0.5
  - cosine:
      lr_end: 1e-6
      epoch_end: 35

